# Generated by Django 5.0.6 on 2024-07-07 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_remove_budget_items"),
        ("orcamento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractitem",
            name="budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget.budget",
            ),
        ),
    ]
