# Generated by Django 5.0.6 on 2024-07-07 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamento", "0002_abstractitem_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "abstractitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="orcamento.abstractitem",
                    ),
                ),
            ],
            bases=("orcamento.abstractitem",),
        ),
        migrations.AddField(
            model_name="abstractitem",
            name="is_fixed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Revenue",
            fields=[],
            options={
                "verbose_name": "Revenue",
                "verbose_name_plural": "Revenues",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orcamento.transaction",),
        ),
        migrations.CreateModel(
            name="Spent",
            fields=[],
            options={
                "verbose_name": "Spent",
                "verbose_name_plural": "Spents",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orcamento.transaction",),
        ),
    ]
